### ISSUE TITLE
Pressing "Speichern" (Save) multiple times when creating a homework with attachment will create the homework multiple times.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#625] opened 2023-04-21 12:00 UTC
## Describe the bug
When creating a homework with an attachment and pressing "Speichern" (Save) several times not one but multiple identical homeworks will be created.

## Steps to reproduce the bug

1. Go to homework page
2. Open homework creation dialog
3. Fill in necessary details (title, course, etc)
4. Add an attachment
5. Press "Speichern" multiple times quickly

## Current _broken_ behavior
An identical homework will be created several times.

## Expected behavior
Only one homework will be created

## Tested device

- Device: PC

- OS: Windows 11

- App type: Web app

- App version: Alpha Web app (1.6.2 (318)) commit 2213680f49bed09c4f04160d1b514718fedb1eb4

**Comment by nilsreichardt** [comment] 2024-08-11 13:35
Duplicate of #1117

**Closed by nilsreichardt** 2024-08-11 13:35 UTC
Labels: bug, good first issue, feature: homework, w: add-homework-page
